apiVersion: v1
kind: Namespace
metadata:
  name: chainlens-crypto
  labels:
    name: chainlens-crypto
    environment: production
    team: chainlens
    project: crypto-services
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: chainlens-crypto-quota
  namespace: chainlens-crypto
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: chainlens-crypto-limits
  namespace: chainlens-crypto
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    type: Container
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: Container
