version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sentiment-postgres
    environment:
      POSTGRES_DB: sentiment_analysis
      POSTGRES_USER: chainlens
      POSTGRES_PASSWORD: chainlens123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chainlens -d sentiment_analysis"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
