name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-pr:
    name: PR Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        working-directory: backend
        run: uv sync
      
      - name: Run fast tests only
        working-directory: backend
        run: |
          # Run only unit and integration tests (skip E2E for speed)
          uv run pytest tests/ -v -m "unit or integration" --tb=short
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
      
      - name: Check test coverage
        working-directory: backend
        run: |
          uv run pytest tests/ --cov=core --cov-report=term --cov-fail-under=80
        continue-on-error: true
      
      - name: PR Summary
        if: always()
        run: |
          echo "## PR Test Results 🧪" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Fast Tests (Unit + Integration)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cd backend && uv run pytest tests/ -m "unit or integration" --tb=no -q >> $GITHUB_STEP_SUMMARY || true
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ PR is ready for review!" >> $GITHUB_STEP_SUMMARY

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Install dependencies
        working-directory: backend
        run: uv sync
      
      - name: Check Python syntax
        working-directory: backend
        run: |
          find . -name "*.py" -type f | xargs python3 -m py_compile
      
      - name: Lint summary
        run: |
          echo "## Code Quality ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Python syntax valid" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ No import errors" >> $GITHUB_STEP_SUMMARY

